### PR TITLE
Stage 1 report for Group 8

### PR DESCRIPTION
**Pull request by sheroze1123**
Project report can be found [here.](https://github.com/sheroze1123/water/blob/master/report/report.pdf)

We cannot attach the pdf directly because GitHub says that we need 'write permission to this repository'.

### CODE REVIEW

**Comment by calvinwylie** [comment]
# 

#  Review from Group 6 (For Group 8)
1. Strengths
- I like your solution for wave speed synchronization.  
- Good job on the vectorization but it would be interesting to look at 
  why compute_step became much slower.
- It's good that you are thinking about domain decomposition.
1. Potential Improvements
- Wasn't quite clear on how you changed memory layout in Section 2.1.  
  I understood after reading further in your report but it could be explained
  better up front. 
1. Additional Comments
- It would be nice to have some excerpts of your vectorization report in the 
  report so that I don't have to go to your repository to see it.

**Comment by ww382** [comment]
Review from Group 7

Strength:
- Good idea that you use #pragma simd for vectorization
- I like how your setup for domain decomposition

Improvement:
- You might also want to try to use #pragma ivdep to fix some FLOW and ANTI dependence

**Comment by TJSong** [comment]
Review from Group 7
- Strength : 
  We liked study about scaling.
  It is nice to see this with cool graphs.
  Detailed domain decomposition part is great.
- Things to be improved :
  You might try with different "nx".
  It is better to have some graphs or plots to show your performance improvement against baseline.

**Comment by sheroze1123** [comment]
Closing pull request to open final report pull request.

**Pull request closed without merging**
